/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imagesort;

import com.drew.imaging.ImageProcessingException;
import imagesort.file.FileManager;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Calendar;
import java.util.Optional;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void test(String path) throws ImageProcessingException, IOException {
        var file = Path.of(path);
        var fm = new FileManager();
        Optional<Calendar> opt = fm.getDate(file.toFile());
        opt.ifPresent(System.out::println);

        /*
        FileManager fm = new FileManager();
        var files = fm.getFiles(path);
        files.forEach(file -> {
            System.out.println(file);
            try {
//                FileManager.readImageMetadata(file.toFile());
                fm.getDate(file.toFile());
            } catch (ImageProcessingException | IOException e) {
                throw new RuntimeException(e);
            }
        });
         */
    }

    public static void main(String[] args) throws ImageProcessingException, IOException {
    }
}
