/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imagesort;

import com.drew.imaging.ImageProcessingException;
import imagesort.file.FileManager;
import imagesort.file.ImageFile;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void testOne(String path) throws ImageProcessingException, IOException {
        var file = Path.of(path);
        new ImageFile(file).move();
//        new ImageFile(file).printAllMetadata();
    }
    public static void testAll(String path) throws IOException {
        FileManager fm = new FileManager(path);
        fm.moveAllImages();
    }

    public static void main(String[] args) throws ImageProcessingException, IOException {
    }
}
